### PR TITLE
Improved mass_mailer

### PR DESCRIPTION
**Pull request by lf32**
This script includes few improvements:
- It checks if the addrfile and msg file exist before proceeding, which will prevent errors if the files are not found.
- Instead of using backticks, it uses a while loop to read addresses from the addrfile, which is more readable and safer.

### CODE REVIEW

**Review by gregkh — CHANGES_REQUESTED** [review]
Please squash this into the previous commit.  Never do one thing and then fix it up in a follow-on commit, that way is not normally a good thing :)

**Comment by lf32** [comment]
Thanks @gregkh for reminding this.

**Comment by lf32** [comment]
> Please squash this into the previous commit. Never do one thing and then fix it up in a follow-on commit, that way is not normally a good thing :)

Thanks @gregkh, sure will squash them!

**Comment by lf32** [comment]
I am closing this since I have made a force push.

**Pull request closed without merging**
